cabin(nico).
cabin(kraakli).
cabin(lynhoegen).
cabin(flaa).
cabin(morten).
access(fremo).
access(langlete).
access(broettem).
access(lundamo).
trip(fremo,nico,3).
trip(nico,kraakli,2).
trip(kraakli,lynhoegen,5).
trip(nico,lynhoegen,5).
trip(kraakli,morten,5).
trip(morten,langlete,4).
trip(flaa,nico,7).
trip(lundamo,flaa,2).
trip(broettem,lynhoegen,4).
trip(lundamo,kraakli,7).
